/**
 * AP grievance training corpus — the installed dataset behind Stage B of the
 * two-stage department classifier (Saarthi 2.0 §8.2).
 *
 * Each row is a real-shaped, human-labelled grievance utterance in the mix the
 * pilot actually receives: English, Telugu, romanised Telugu and Hindi, across
 * ALL fifteen routable departments. Stage B is a TF-IDF k-nearest-neighbour
 * model over this corpus (word + bigram + character n-gram features) fused with
 * taxonomy/KB keyword signals and temperature-scaled into a calibrated softmax.
 * Every human correction is appended to `TrainingEvent` and folded back into
 * the index at inference time — the active-learning loop that keeps the model
 * improving with every verified decision (the pilot-scale stand-in for the
 * MuRIL/IndicBERT fine-tune described in the spec; same interface, same gate).
 */

export interface CorpusExample {
  deptId: string;
  text: string;
}

export const AP_GRIEVANCE_CORPUS: CorpusExample[] = [
  // ── RWS — Rural Water Supply ──────────────────────────────────────────────
  { deptId: 'RWS', text: 'No drinking water in our village for five days, borewell motor burnt' },
  { deptId: 'RWS', text: 'మా ఊరిలో తాగునీరు రావడం లేదు, బోరు చెడిపోయింది' },
  { deptId: 'RWS', text: 'Hand pump broken near the school, children have no water to drink' },
  { deptId: 'RWS', text: 'water tanker is not coming to our hamlet since one week' },
  { deptId: 'RWS', text: 'pipeline leakage on main road, water being wasted, low pressure in taps' },
  { deptId: 'RWS', text: 'oorilo neellu ravatledu boru pani cheyatledu' },
  { deptId: 'RWS', text: 'taagu neellu leka ibbandi padutunnamu tanker pampandi' },
  { deptId: 'RWS', text: 'overhead tank not being filled, taps dry every morning' },
  { deptId: 'RWS', text: 'हमारे गांव में पीने का पानी नहीं आ रहा है, बोरवेल खराब है' },
  { deptId: 'RWS', text: 'पानी की टंकी से सप्लाई बंद है, नल सूखे पड़े हैं' },
  { deptId: 'RWS', text: 'dirty smelly water coming from the tap, people falling sick after drinking' },
  { deptId: 'RWS', text: 'తాగు నీటి పైపులైన్ పగిలింది, నీళ్లు కలుషితం అవుతున్నాయి' },
  { deptId: 'RWS', text: 'borewell dried up in summer, need new bore for drinking water scheme' },
  { deptId: 'RWS', text: 'water supply comes only once in four days, not enough for the family' },
  { deptId: 'RWS', text: 'మంచినీటి పథకం పనులు ఆగిపోయాయి, ఇంటింటికి నల్లా రాలేదు' },
  { deptId: 'RWS', text: 'contaminated water causing stomach problems, no chlorination being done' },
  { deptId: 'RWS', text: 'summer water scarcity, women walking two kilometres to fetch drinking water' },
  { deptId: 'RWS', text: 'బోరు మోటర్ కాలిపోయి వారం అయింది, ఎవరూ బాగు చేయలేదు' },
  { deptId: 'RWS', text: 'new water connection to our house not given even after paying the fee' },
  { deptId: 'RWS', text: 'tap water motham mud vastundi, filter cheyandi' },
  { deptId: 'RWS', text: 'జల్ జీవన్ మిషన్ కింద నల్లా ఇచ్చారు కానీ నీళ్లు రావు' },
  { deptId: 'RWS', text: 'public tap platform broken, water stagnating and mosquitoes breeding' },
  { deptId: 'RWS', text: 'हैंडपंप छह महीने से खराब पड़ा है, मरम्मत नहीं हुई' },
  { deptId: 'RWS', text: 'water man opens the valve late, upper street never gets drinking water' },

  // ── ENERGY — power distribution ───────────────────────────────────────────
  { deptId: 'ENERGY', text: 'No power supply since yesterday morning, transformer sparking' },
  { deptId: 'ENERGY', text: 'కరెంటు పోయింది, ట్రాన్స్‌ఫార్మర్ కాలిపోయింది' },
  { deptId: 'ENERGY', text: 'frequent power cuts every evening, motors and fans not working' },
  { deptId: 'ENERGY', text: 'electric pole leaning dangerously after the storm, wire hanging low' },
  { deptId: 'ENERGY', text: 'live wire fell on the road near the school, very dangerous' },
  { deptId: 'ENERGY', text: 'current bill chala ekkuva vachindi, meter reading wrong' },
  { deptId: 'ENERGY', text: 'karentu poyindi rendu rojula nundi, transformer repair cheyandi' },
  { deptId: 'ENERGY', text: 'high electricity bill this month, meter seems faulty, please check' },
  { deptId: 'ENERGY', text: 'బిల్లు తప్పుగా వచ్చింది, మీటర్ రీడింగ్ సరిగా తీయలేదు' },
  { deptId: 'ENERGY', text: 'बिजली नहीं है दो दिन से, ट्रांसफार्मर जल गया है' },
  { deptId: 'ENERGY', text: 'खंभे का तार ढीला लटक रहा है, बच्चों के लिए खतरा है' },
  { deptId: 'ENERGY', text: 'low voltage problem, lights very dim at night, appliances damaged' },
  { deptId: 'ENERGY', text: 'new electricity connection applied three months ago still not given' },
  { deptId: 'ENERGY', text: 'విద్యుత్ స్తంభం వంగిపోయింది, తీగలు కిందకు వేలాడుతున్నాయి' },
  { deptId: 'ENERGY', text: 'agriculture power supply given only three hours, crops drying' },
  { deptId: 'ENERGY', text: 'street transformer fuse blows every day, half the village in darkness' },
  { deptId: 'ENERGY', text: 'meter burnt due to fluctuation, replacement pending for weeks' },
  { deptId: 'ENERGY', text: 'కొత్త కరెంటు కనెక్షన్ కోసం దరఖాస్తు చేసి నెలలైంది' },
  { deptId: 'ENERGY', text: 'electric shock risk near the water tank, junction box open' },
  { deptId: 'ENERGY', text: 'power cut during exams every night, please fix the feeder problem' },
  { deptId: 'ENERGY', text: 'మా వీధిలో వోల్టేజ్ తక్కువగా ఉంది, పంపు మోటార్ నడవడం లేదు' },
  { deptId: 'ENERGY', text: 'bill paid but supply disconnected wrongly, reconnect immediately' },
  { deptId: 'ENERGY', text: 'बिजली का बिल दोगुना आया है, मीटर की जांच करवाएं' },

  // ── CS — Civil Supplies / ration ──────────────────────────────────────────
  { deptId: 'CS', text: 'My ration card is blocked, not getting rice this month' },
  { deptId: 'CS', text: 'రేషన్ కార్డు పనిచేయడం లేదు, బియ్యం ఇవ్వడం లేదు' },
  { deptId: 'CS', text: 'ration dealer giving less quantity, weighing machine seems wrong' },
  { deptId: 'CS', text: 'fingerprint not working at ration shop, ekyc failure, no rice given' },
  { deptId: 'CS', text: 'ration shop dealer asking extra money for rice bags' },
  { deptId: 'CS', text: 'kalthi biyyam poor quality rice full of stones and worms' },
  { deptId: 'CS', text: 'ration biyyam ivvatledu card block ayindi antunnaru' },
  { deptId: 'CS', text: 'new ration card application pending since six months' },
  { deptId: 'CS', text: 'राशन कार्ड बंद हो गया है, चावल नहीं मिल रहा' },
  { deptId: 'CS', text: 'राशन डीलर कम तौल रहा है, शिकायत करने पर धमकाता है' },
  { deptId: 'CS', text: 'రేషన్ డీలర్ సమయానికి షాప్ తెరవడం లేదు, సరుకులు ఇవ్వడం లేదు' },
  { deptId: 'CS', text: 'name deleted from ration card wrongly, need to add family member' },
  { deptId: 'CS', text: 'fair price shop closed for two weeks, no rice or sugar distributed' },
  { deptId: 'CS', text: 'రేషన్ షాపులో సరుకులు నెలాఖరుకే అయిపోతున్నాయి, అందరికీ రావడం లేదు' },
  { deptId: 'CS', text: 'ration portability not working, migrated for work and cannot draw rice' },
  { deptId: 'CS', text: 'epos machine always server down, dealer sends us back every time' },
  { deptId: 'CS', text: 'card lo pere thappuga undi, correction cheyali' },
  { deptId: 'CS', text: 'కొత్త రేషన్ కార్డు కోసం అప్లై చేసి ఆరు నెలలు అయింది' },
  { deptId: 'CS', text: 'kerosene not supplied to card holders in our village this quarter' },
  { deptId: 'CS', text: 'रिक्शन की दुकान पर अंगूठा नहीं लग रहा, चावल नहीं दे रहे' },
  { deptId: 'CS', text: 'dealer diverting PDS rice to black market, stocks vanish overnight' },
  { deptId: 'CS', text: 'రేషన్ సరుకులో చక్కెర, కందిపప్పు ఇవ్వడం లేదు' },

  // ── PEN — Pensions & welfare ──────────────────────────────────────────────
  { deptId: 'PEN', text: 'My old age pension stopped, not received for three months' },
  { deptId: 'PEN', text: 'పెన్షన్ ఆగిపోయింది, మూడు నెలలుగా డబ్బులు పడలేదు' },
  { deptId: 'PEN', text: 'widow pension application pending, no response from secretariat' },
  { deptId: 'PEN', text: 'pension amount short credited, got 2000 instead of 3000' },
  { deptId: 'PEN', text: 'disability pension rejected wrongly, I have sadarem certificate' },
  { deptId: 'PEN', text: 'pension raledu ee nela, bank account lo padaledu' },
  { deptId: 'PEN', text: 'पेंशन तीन महीने से नहीं मिली है, कृपया मदद करें' },
  { deptId: 'PEN', text: 'विधवा पेंशन का आवेदन एक साल से लंबित है' },
  { deptId: 'PEN', text: 'life certificate ekyc done but pension still not restarted' },
  { deptId: 'PEN', text: 'వృద్ధాప్య పింఛను కొత్త దరఖాస్తు మంజూరు కాలేదు' },
  { deptId: 'PEN', text: 'pension stopped saying I am ineligible but I am 68 years old' },
  { deptId: 'PEN', text: 'volunteer is not bringing pension to my door, I am bedridden' },
  { deptId: 'PEN', text: 'na bharta chanipoyadu widow pension kosam apply chesanu inka raledu' },
  { deptId: 'PEN', text: 'దివ్యాంగుల పింఛను కోసం సదరం సర్టిఫికెట్ ఉన్నా తిరస్కరించారు' },
  { deptId: 'PEN', text: 'pension card shows active but amount never comes to my account' },
  { deptId: 'PEN', text: 'aadhaar seeding problem in bank, pension credit failing every month' },
  { deptId: 'PEN', text: 'పింఛను డబ్బులు వాలంటీర్ ఇవ్వకుండా వెనక్కి పంపిస్తున్నారు' },
  { deptId: 'PEN', text: 'बुढ़ापा पेंशन की राशि आधी ही आई है इस महीने' },
  { deptId: 'PEN', text: 'transferred my pension after moving village, still going to old address' },
  { deptId: 'PEN', text: 'scholarship for my daughter not credited under welfare scheme' },

  // ── REVENUE — land records & certificates ─────────────────────────────────
  { deptId: 'REVENUE', text: 'Land mutation pending for one year, survey number 123/4A' },
  { deptId: 'REVENUE', text: 'భూమి మ్యుటేషన్ కాలేదు, పట్టా పేరు మారలేదు' },
  { deptId: 'REVENUE', text: 'caste certificate application rejected without any reason' },
  { deptId: 'REVENUE', text: 'income certificate delayed, needed for college admission urgently' },
  { deptId: 'REVENUE', text: 'neighbour encroached on my land, survey not being done' },
  { deptId: 'REVENUE', text: 'adangal and 1B record showing wrong extent, correction needed' },
  { deptId: 'REVENUE', text: 'जमीन का म्यूटेशन नहीं हुआ है, पटवारी सुनता नहीं' },
  { deptId: 'REVENUE', text: 'जाति प्रमाण पत्र दो महीने से लंबित है, कॉलेज में चाहिए' },
  { deptId: 'REVENUE', text: 'patta transfer aagipoindi, tahsildar office chuttu tirugutunnanu' },
  { deptId: 'REVENUE', text: 'na bhoomi survey cheyamani application pettanu evaru raledu' },
  { deptId: 'REVENUE', text: 'పట్టాదారు పాసుపుస్తకం తప్పులతో వచ్చింది, సరిచేయాలి' },
  { deptId: 'REVENUE', text: 'land records show my farm in another person name, webland mistake' },
  { deptId: 'REVENUE', text: 'sub division of inherited land pending, brothers cannot get separate patta' },
  { deptId: 'REVENUE', text: 'residence certificate for army application not issued in time' },
  { deptId: 'REVENUE', text: 'మా పొలం సరిహద్దు వివాదం, సర్వేయర్ రావడం లేదు' },
  { deptId: 'REVENUE', text: 'government assigned land occupied by others, no enquiry conducted' },
  { deptId: 'REVENUE', text: 'ఆదాయ ధృవీకరణ పత్రం కోసం మీసేవలో అప్లై చేసి నెల అయింది' },
  { deptId: 'REVENUE', text: 'RoR correction application bounced between VRO and tahsildar office' },
  { deptId: 'REVENUE', text: 'भूमि रिकॉर्ड में रकबा गलत दर्ज है, सुधार कराएं' },
  { deptId: 'REVENUE', text: 'illegal occupation on the lake bund poramboke land, revenue not acting' },

  // ── PR — Panchayat Raj (streetlights, drains, garbage, village works) ─────
  { deptId: 'PR', text: 'Streetlights not working on our lane for ten days, very dark at night unsafe' },
  { deptId: 'PR', text: 'వీధి దీపాలు వెలగడం లేదు, రాత్రి చీకటిగా ఉంది, భయంగా ఉంది' },
  { deptId: 'PR', text: 'drainage overflowing near our houses, mosquitoes and bad smell' },
  { deptId: 'PR', text: 'garbage not collected for two weeks, heap growing near the temple' },
  { deptId: 'PR', text: 'village internal cc road full of mud, cannot walk in rain' },
  { deptId: 'PR', text: 'mgnrega wages not paid for the work done last month' },
  { deptId: 'PR', text: 'street light repair cheyandi, mottham veedhi antha cheekati' },
  { deptId: 'PR', text: 'drainage kampu vastundi intla mundu, clean cheyinchandi' },
  { deptId: 'PR', text: 'नाली का पानी सड़क पर बह रहा है, सफाई नहीं होती' },
  { deptId: 'PR', text: 'गांव में कचरा नहीं उठाया जा रहा, गंदगी फैली है' },
  { deptId: 'PR', text: 'డ్రైనేజీ పొంగి పొర్లుతోంది, పరిశుభ్రత లేదు, దోమలు పెరిగాయి' },
  { deptId: 'PR', text: 'sanitation worker not coming, garbage dump near school gate' },
  { deptId: 'PR', text: 'panchayat tap stand posts rusted and falling, repair needed' },
  { deptId: 'PR', text: 'గ్రామ పంచాయతీ సీసీ రోడ్డు పనులు మధ్యలో ఆపేశారు' },
  { deptId: 'PR', text: 'job card renewal pending, upadhi hami pani ivvatledu' },
  { deptId: 'PR', text: 'community hall roof leaking, panchayat not repairing' },
  { deptId: 'PR', text: 'burial ground has no road or fence, panchayat ignoring requests' },
  { deptId: 'PR', text: 'వీధి కుళాయి దగ్గర మురుగు నీరు నిలిచి దుర్వాసన వస్తోంది' },
  { deptId: 'PR', text: 'open drain uncovered near anganwadi, small children may fall' },
  { deptId: 'PR', text: 'mgnrega muster lo na peru lekunda chesaru, kuli dabbulu raledu' },
  { deptId: 'PR', text: 'मनरेगा की मजदूरी दो महीने से नहीं मिली है' },
  { deptId: 'PR', text: 'dustbins never emptied on our street, dogs scattering waste everywhere' },

  // ── MA — Municipal Administration (towns: tax, wards, sewerage, permits) ──
  { deptId: 'MA', text: 'Property tax assessed double for my house, municipal office not correcting' },
  { deptId: 'MA', text: 'మునిసిపల్ ఆస్తి పన్ను తప్పుగా వేశారు, సరిచేయాలి' },
  { deptId: 'MA', text: 'building permission application pending in town planning for months' },
  { deptId: 'MA', text: 'manhole overflowing on 4th ward main road, sewage on the street' },
  { deptId: 'MA', text: 'municipal garbage lorry skips our ward, bins overflowing in the colony' },
  { deptId: 'MA', text: 'birth certificate correction pending at the municipal office' },
  { deptId: 'MA', text: 'मुनिसिपल टैक्स ज्यादा लगाया गया है, ठीक कराएं' },
  { deptId: 'MA', text: 'वार्ड में सीवर लाइन जाम है, गंदा पानी घरों में घुस रहा है' },
  { deptId: 'MA', text: 'footpath encroached by shops in the market area, walkers on the road' },
  { deptId: 'MA', text: 'మున్సిపాలిటీలో డెత్ సర్టిఫికెట్ ఇవ్వడానికి ఆలస్యం చేస్తున్నారు' },
  { deptId: 'MA', text: 'town water tax bill wrong, paid already but showing due' },
  { deptId: 'MA', text: 'ward sanitation staff not sweeping the streets, commissioner not responding' },
  { deptId: 'MA', text: 'municipality park unmaintained, broken swings and open gate' },
  { deptId: 'MA', text: 'sewerage connection to new house not given by the municipality' },
  { deptId: 'MA', text: 'కార్పొరేషన్ వారు అనుమతి లేకుండా షాపుల ముందు ఆక్రమణలు తొలగించడం లేదు' },
  { deptId: 'MA', text: 'trade licence renewal delayed at the municipal office, shop at risk' },
  { deptId: 'MA', text: 'unauthorized construction next door blocking light, town planning silent' },
  { deptId: 'MA', text: 'municipal septic tanker service booked but never came to the ward' },

  // ── RB — Roads & Buildings (major roads, bridges, highways) ───────────────
  { deptId: 'RB', text: 'Main road to the mandal full of big potholes, buses skidding, accidents happening' },
  { deptId: 'RB', text: 'రహదారి పూర్తిగా పాడైంది, పెద్ద గుంతలు, ప్రమాదాలు జరుగుతున్నాయి' },
  { deptId: 'RB', text: 'bridge over the stream damaged, railing broken, dangerous for vehicles' },
  { deptId: 'RB', text: 'culvert collapsed after rains, village cut off from the highway' },
  { deptId: 'RB', text: 'road dug up for pipeline six months ago, never restored' },
  { deptId: 'RB', text: 'speed breakers needed near the school on the main road, vehicles too fast' },
  { deptId: 'RB', text: 'सड़क पर बड़े गड्ढे हैं, हादसे हो रहे हैं, मरम्मत कराएं' },
  { deptId: 'RB', text: 'पुल की रेलिंग टूटी है, वाहन गिरने का खतरा है' },
  { deptId: 'RB', text: 'main road meeda pedda gunthalu unnayi, bike accidents avtunnayi' },
  { deptId: 'RB', text: 'ghat road side wall collapsed, lorries passing dangerously close to edge' },
  { deptId: 'RB', text: 'మండలానికి వెళ్లే ప్రధాన రహదారి వర్షాలకు కొట్టుకుపోయింది' },
  { deptId: 'RB', text: 'highway service road blocked with debris after widening work stopped' },
  { deptId: 'RB', text: 'no road signs or markings on the accident-prone curve near our village' },
  { deptId: 'RB', text: 'వంతెన పైన గుంతలు పడ్డాయి, భారీ వాహనాలకు ప్రమాదం' },
  { deptId: 'RB', text: 'tar road laid last year already peeled off, poor quality work' },
  { deptId: 'RB', text: 'daily bus route road so damaged that RTC threatened to stop service' },
  { deptId: 'RB', text: 'road widening left deep open trenches beside the carriageway unmarked' },

  // ── HEALTH ────────────────────────────────────────────────────────────────
  { deptId: 'HEALTH', text: 'No doctor at the PHC for a week, patients returning without treatment' },
  { deptId: 'HEALTH', text: 'ఆసుపత్రిలో డాక్టర్ లేరు, మందులు ఇవ్వడం లేదు' },
  { deptId: 'HEALTH', text: 'medicines out of stock at government hospital, asked to buy outside' },
  { deptId: 'HEALTH', text: '108 ambulance came very late, patient condition became serious' },
  { deptId: 'HEALTH', text: 'dengue fever cases increasing in our village, no fogging done' },
  { deptId: 'HEALTH', text: 'aarogyasri treatment denied by the private hospital wrongly' },
  { deptId: 'HEALTH', text: 'सरकारी अस्पताल में दवाई नहीं मिल रही, डॉक्टर नहीं आते' },
  { deptId: 'HEALTH', text: 'एंबुलेंस समय पर नहीं आई, मरीज की हालत बिगड़ गई' },
  { deptId: 'HEALTH', text: 'phc lo doctor undadu, nurse matrame untundi, treatment dorakatledu' },
  { deptId: 'HEALTH', text: 'government hospital toilet and ward very dirty, infection risk' },
  { deptId: 'HEALTH', text: 'ఆరోగ్యశ్రీ కార్డు ఉన్నా ఆపరేషన్ చేయడానికి డబ్బులు అడుగుతున్నారు' },
  { deptId: 'HEALTH', text: 'anganwadi nutrition kits not distributed to pregnant women this month' },
  { deptId: 'HEALTH', text: 'vaccination camp cancelled twice, children missing due doses' },
  { deptId: 'HEALTH', text: 'జ్వరాలు పెరుగుతున్నాయి, వైద్య శిబిరం పెట్టాలి, దోమల మందు కొట్టాలి' },
  { deptId: 'HEALTH', text: 'x-ray machine at area hospital broken for months, referred to private scan' },
  { deptId: 'HEALTH', text: 'asha worker positions vacant, no antenatal checkups happening in village' },
  { deptId: 'HEALTH', text: 'मलेरिया फैल रहा है, छिड़काव नहीं हुआ है गांव में' },

  // ── EDU — School Education ────────────────────────────────────────────────
  { deptId: 'EDU', text: 'Only two teachers for five classes in our government school' },
  { deptId: 'EDU', text: 'మా ప్రభుత్వ పాఠశాలలో ఉపాధ్యాయులు సరిపడా లేరు' },
  { deptId: 'EDU', text: 'mid day meal quality very bad, children found worms in the food' },
  { deptId: 'EDU', text: 'school building roof leaking, classes held under the tree' },
  { deptId: 'EDU', text: 'amma vodi amount not credited for my daughter this year' },
  { deptId: 'EDU', text: 'textbooks and uniforms not supplied even after two months of school opening' },
  { deptId: 'EDU', text: 'स्कूल में शिक्षक नहीं आते, बच्चों की पढ़ाई खराब हो रही है' },
  { deptId: 'EDU', text: 'मिड डे मील में खाना खराब मिल रहा है, बच्चे बीमार पड़े' },
  { deptId: 'EDU', text: 'school lo toilets pani cheyavu, ammayilu ibbandi padutunnaru' },
  { deptId: 'EDU', text: 'headmaster denying admission asking for donation in government school' },
  { deptId: 'EDU', text: 'పాఠశాలలో మరుగుదొడ్లు శిథిలావస్థలో ఉన్నాయి, తాగునీరు లేదు' },
  { deptId: 'EDU', text: 'scholarship for SC students pending since last academic year' },
  { deptId: 'EDU', text: 'school compound wall collapsed, stray dogs entering the playground' },
  { deptId: 'EDU', text: 'బడికి వెళ్లే పిల్లలకు బస్సు సౌకర్యం లేదు, ఐదు కిలోమీటర్లు నడుస్తున్నారు' },
  { deptId: 'EDU', text: 'teacher transferred six months ago, replacement not posted, single teacher school' },
  { deptId: 'EDU', text: 'vidya kanuka kits incomplete, no shoes or notebooks given' },
  { deptId: 'EDU', text: 'सरकारी स्कूल में बेंच नहीं हैं, बच्चे जमीन पर बैठते हैं' },

  // ── AGRI — Agriculture & allied ───────────────────────────────────────────
  { deptId: 'AGRI', text: 'Rythu bharosa amount not credited to my account this season' },
  { deptId: 'AGRI', text: 'రైతు భరోసా డబ్బులు నా ఖాతాలో పడలేదు' },
  { deptId: 'AGRI', text: 'crop insurance claim for failed groundnut crop still pending' },
  { deptId: 'AGRI', text: 'urea not available at the RBK, black market selling at double price' },
  { deptId: 'AGRI', text: 'spurious cotton seeds sold to farmers, crop failed completely' },
  { deptId: 'AGRI', text: 'pm kisan installment stopped after ekyc, land records are correct' },
  { deptId: 'AGRI', text: 'फसल बीमा का पैसा नहीं मिला, सूखे से फसल खराब हुई थी' },
  { deptId: 'AGRI', text: 'खाद की दुकान पर यूरिया नहीं मिल रहा, कालाबाजारी हो रही है' },
  { deptId: 'AGRI', text: 'pattalu correct ga unna rythu bharosa raledu, e-crop lo problem antunnaru' },
  { deptId: 'AGRI', text: 'boru meeda vyavasayam, current sariga ivvaka panta endipotondi' },
  { deptId: 'AGRI', text: 'వర్షాలకు పంట నష్టం జరిగింది, ఇన్‌పుట్ సబ్సిడీ ఇంకా రాలేదు' },
  { deptId: 'AGRI', text: 'e-crop booking not done by the field officer, missed the insurance window' },
  { deptId: 'AGRI', text: 'tenant farmer certificate not issued, cannot access crop loan' },
  { deptId: 'AGRI', text: 'ఆర్బీకేలో విత్తనాలు సమయానికి ఇవ్వలేదు, విత్తనం ఆలస్యం అయింది' },
  { deptId: 'AGRI', text: 'paddy procurement centre delaying payment for the grain already given' },
  { deptId: 'AGRI', text: 'pest attack on chilli crop, agriculture officer never visited for advisory' },
  { deptId: 'AGRI', text: 'धान की खरीद का भुगतान एक महीने से अटका है' },

  // ── POLICE — law & order ──────────────────────────────────────────────────
  { deptId: 'POLICE', text: 'Police station refusing to register FIR for my stolen motorcycle' },
  { deptId: 'POLICE', text: 'పోలీసులు ఎఫ్‌ఐఆర్ నమోదు చేయడం లేదు, దొంగతనం జరిగింది' },
  { deptId: 'POLICE', text: 'rowdy elements harassing shopkeepers for money, no patrolling at night' },
  { deptId: 'POLICE', text: 'complaint given one month ago about land threat, no action taken' },
  { deptId: 'POLICE', text: 'cybercrime fraud took 50000 from my bank account, case not moving' },
  { deptId: 'POLICE', text: 'eve teasing near the girls college, police not responding to calls' },
  { deptId: 'POLICE', text: 'पुलिस एफआईआर दर्ज नहीं कर रही है, चोरी हुई है घर में' },
  { deptId: 'POLICE', text: 'शराब पीकर रात में हंगामा होता है, गश्त बढ़ाई जाए' },
  { deptId: 'POLICE', text: 'na complaint teesukoni nela ayindi, police station lo action ledu' },
  { deptId: 'POLICE', text: 'illegal liquor being sold openly in the village, police ignoring' },
  { deptId: 'POLICE', text: 'మా అమ్మాయిని వేధిస్తున్నారు, పోలీసులు పట్టించుకోవడం లేదు' },
  { deptId: 'POLICE', text: 'neighbour attacked my father over boundary dispute, FIR delayed' },
  { deptId: 'POLICE', text: 'online job fraud case, cyber cell not updating on the investigation' },
  { deptId: 'POLICE', text: 'రాత్రి పూట గస్తీ లేదు, వరుస దొంగతనాలు జరుగుతున్నాయి' },
  { deptId: 'POLICE', text: 'missing person complaint filed, no search update from the station' },
  { deptId: 'POLICE', text: 'traffic constable demanding money from auto drivers at the junction' },

  // ── TRANSPORT — RTA / RTC ─────────────────────────────────────────────────
  { deptId: 'TRANSPORT', text: 'Driving licence renewal pending for two months at the RTA office' },
  { deptId: 'TRANSPORT', text: 'డ్రైవింగ్ లైసెన్స్ కోసం అప్లై చేసి రెండు నెలలు అయింది' },
  { deptId: 'TRANSPORT', text: 'RTC bus to our village cancelled, students cannot reach college' },
  { deptId: 'TRANSPORT', text: 'vehicle RC transfer stuck, showing pending in the portal forever' },
  { deptId: 'TRANSPORT', text: 'no evening bus from the mandal, workers stranded till night' },
  { deptId: 'TRANSPORT', text: 'आरटीए में लाइसेंस के लिए स्लॉट नहीं मिल रहा, एजेंट पैसे मांगते हैं' },
  { deptId: 'TRANSPORT', text: 'गांव के लिए बस सेवा बंद कर दी गई है, बहाल कराएं' },
  { deptId: 'TRANSPORT', text: 'bus depot vallu route marchesaru, school pillalaku ibbandi' },
  { deptId: 'TRANSPORT', text: 'మా ఊరికి ఆర్టీసీ బస్సు సర్వీసు లేదు, పది కిలోమీటర్లు నడవాలి' },
  { deptId: 'TRANSPORT', text: 'fitness certificate for my auto pending, inspector not available' },
  { deptId: 'TRANSPORT', text: 'RC card printed with wrong engine number, correction not happening' },
  { deptId: 'TRANSPORT', text: 'school bus overloaded and speeding, RTA should inspect' },
  { deptId: 'TRANSPORT', text: 'బస్ పాస్ కౌంటర్ పనిచేయడం లేదు, విద్యార్థుల పాసులు రావడం లేదు' },
  { deptId: 'TRANSPORT', text: 'learner licence test slot booking site always fails at payment' },
  { deptId: 'TRANSPORT', text: 'private buses charging double fare on festival days, no checking' },

  // ── HOUSING — Pedalandariki Illu / PMAY ───────────────────────────────────
  { deptId: 'HOUSING', text: 'House construction first installment received but second installment stuck' },
  { deptId: 'HOUSING', text: 'ఇంటి నిర్మాణానికి రెండో విడత డబ్బులు రాలేదు' },
  { deptId: 'HOUSING', text: 'my name missing from the housing beneficiary list though eligible' },
  { deptId: 'HOUSING', text: 'house site patta allotted but plot occupied by someone else' },
  { deptId: 'HOUSING', text: 'pmay house sanctioned two years ago, geo tagging not done, no funds' },
  { deptId: 'HOUSING', text: 'आवास योजना की किस्त नहीं आई, मकान आधा बना पड़ा है' },
  { deptId: 'HOUSING', text: 'मकान की सूची में नाम नहीं है, पात्र होने पर भी' },
  { deptId: 'HOUSING', text: 'illu manjuru ayindi kani stalam ivvaledu inka' },
  { deptId: 'HOUSING', text: 'పేదలందరికీ ఇళ్లు పథకంలో నా దరఖాస్తు తిరస్కరించారు, కారణం చెప్పలేదు' },
  { deptId: 'HOUSING', text: 'colony layout has no approach road or drainage, houses half done' },
  { deptId: 'HOUSING', text: 'housing site allotment letter given but boundaries never marked' },
  { deptId: 'HOUSING', text: 'ఇంటి స్థలం పట్టా కోసం ఏళ్లుగా ఎదురు చూస్తున్నాం' },
  { deptId: 'HOUSING', text: 'contractor built weak walls in the scheme house, cracks already forming' },
  { deptId: 'HOUSING', text: 'bill payment for completed house stage pending in housing corporation' },

  // ── VIG — vigilance / corruption ──────────────────────────────────────────
  { deptId: 'VIG', text: 'Official demanded bribe to process my application' },
  { deptId: 'VIG', text: 'లంచం అడుగుతున్నారు, డబ్బు ఇవ్వకపోతే పని చేయరు అంటున్నారు' },
  { deptId: 'VIG', text: 'clerk asking mamool money for issuing certificate, corruption' },
  { deptId: 'VIG', text: 'contractor and officer colluding, fake bills passed for work not done' },
  { deptId: 'VIG', text: 'रिश्वत मांगी जा रही है काम के लिए, शिकायत दर्ज करें' },
  { deptId: 'VIG', text: 'सरकारी योजना का पैसा अधिकारी खा रहे हैं, जांच कराएं' },
  { deptId: 'VIG', text: 'lancham istene pani avtundi antunnaru, illegal collection at office' },
  { deptId: 'VIG', text: 'meeseva operator overcharging for free government services' },
  { deptId: 'VIG', text: 'పనుల్లో నాణ్యత లేకుండా బిల్లులు పాస్ చేసుకుంటున్నారు, విచారణ జరపాలి' },
  { deptId: 'VIG', text: 'ghost workers on the muster roll, wages drawn without any work' },
  { deptId: 'VIG', text: 'officer taking commission from every scheme beneficiary in the village' },
  { deptId: 'VIG', text: 'డబ్బులు ఇవ్వకపోతే ఫైల్ ముందుకు కదలదు అని బహిరంగంగా అంటున్నారు' },
  { deptId: 'VIG', text: 'tender awarded to relative of the officer without open bidding' },
  { deptId: 'VIG', text: 'दफ्तर में बिना पैसे दिए कोई फाइल नहीं बढ़ती' },
];

/** Fold verified human decisions back in at runtime (active-learning loop). */
export function corpusWith(extra: CorpusExample[]): CorpusExample[] {
  return extra.length ? [...AP_GRIEVANCE_CORPUS, ...extra] : AP_GRIEVANCE_CORPUS;
}
