// English is the source of truth for all citizen-facing copy. Every other language
// in translations.ts provides the same keys; missing keys fall back to English.
export const en = {
  // brand / common
  appName: 'SAARTHI',
  tagline: 'Public Grievance Redressal — Guiding Solutions',
  govOfIndia: 'Government of India',
  fullName: 'System for Assisted, Accountable & Responsive Tracking of Hearings & Issues',
  selectLanguage: 'Select your language',
  selectLanguageHelp: 'We will ask every question in the language you choose.',
  language: 'Language',
  continue: 'Continue',
  back: 'Back',
  next: 'Next',
  submit: 'Submit',
  cancel: 'Cancel',
  yes: 'Yes',
  no: 'No',
  ok: 'OK',
  loading: 'Loading…',
  retry: 'Try again',
  optional: 'optional',
  required: 'This is needed',
  callHelpline: 'Call 1902 for help',
  readAloud: 'Read aloud',
  changeLanguage: 'Change language',

  // app navigation (bottom bar + header controls)
  navHome: 'Home',
  navTrack: 'Track',
  navNew: 'New complaint',
  navHeatmap: 'Heatmap',
  navAnalytics: 'Analytics',
  navConsole: 'Console',
  noVoiceHint: 'This device has no voice for your language, so questions cannot be read aloud. Everything still works — please read the questions on screen.',

  // roles / doors
  whoAreYou: 'Who are you?',
  citizen: 'Citizen',
  citizenDesc: 'File a complaint or track its status',
  official: 'Official / Staff',
  officialDesc: 'Officers and Sachivalayam staff sign in',
  openCitizen: 'File or track a complaint',
  openOfficial: 'Staff sign in',

  // citizen login
  citizenSignIn: 'Citizen sign-in',
  enterMobile: 'Enter your mobile number',
  mobilePlaceholder: '10-digit mobile number',
  sendOtp: 'Send code (OTP)',
  otpSent: 'We sent a code to your phone',
  enterOtp: 'Enter the 6-digit code',
  verify: 'Verify & continue',
  resendOtp: 'Resend code',
  loginNoOtpNote: 'No smartphone needed — a Sachivalayam operator can file for you too.',

  // citizen dashboard
  welcome: 'Welcome',
  myComplaints: 'My complaints',
  fileNew: 'File a new complaint',
  fileNewDesc: 'Tell us your problem step by step — speak or type in your language',
  trackTitle: 'Track a complaint',
  trackByNumber: 'Track by complaint number',
  noComplaints: 'You have not filed any complaints yet',
  logout: 'Log out',
  status: 'Status',
  filedOn: 'Filed on',

  // guided form — flow
  formTitle: 'File a complaint',
  stepOf: 'Step {n} of {total}',
  tapToSpeak: 'Tap and speak',
  listening: 'Listening…',
  orTypeHere: 'or type here',
  speakOrType: 'You can speak in your language, or type',

  // guided form — questions
  qName: 'What is your name?',
  qCoName: "Father's or husband's name?",
  qMobile: 'What is your mobile number?',
  qAadhaar: 'Aadhaar number?',
  aadhaarNote: 'Optional. It is kept private and never shown to anyone.',
  qDob: 'Your date of birth?',
  qGender: 'Your gender?',
  optMale: 'Male',
  optFemale: 'Female',
  optOther: 'Other',
  qApplicantType: 'Is this your own problem, or your whole community’s?',
  optIndividual: 'Mine (personal)',
  optCommunity: 'My community',
  qDistrict: 'Which district?',
  qMandal: 'Which mandal?',
  qVillage: 'Which village / ward?',
  qHouseNo: 'House number?',
  qHabitation: 'Habitation / colony?',
  qProblemType: 'What is the problem about?',
  qProblemTypeHelp: 'Pick the closest one — we will confirm it for you.',
  qDescribe: 'Describe your problem',
  qDescribeHelp: 'Speak or type what happened, in your own words.',

  // categories (citizen-friendly)
  catWater: 'Water / borewell',
  catPower: 'Electricity',
  catRation: 'Ration card',
  catPension: 'Pension',
  catLand: 'Land / revenue',
  catOther: 'Something else',

  // review + success
  reviewTitle: 'Please check your details',
  editAnswer: 'Edit',
  confirmSubmit: 'Submit my complaint',
  submitting: 'Submitting…',
  successTitle: 'Complaint filed successfully',
  yourNumber: 'Your complaint number',
  successSms: 'We have sent this number to your phone by SMS.',
  trackNow: 'Track it now',
  fileAnother: 'File another',

  // tracking view
  trackHeading: 'Your complaint',
  integrityVerified: 'Verified & unaltered',
  integrityCheck: 'Check integrity',
  timeline: 'Progress',
  slaLeft: '{n} day(s) left',
  slaOverdue: '{n} day(s) overdue',
  resolvedAsk: 'Is your problem actually solved?',
  resolvedAskNote: 'It will only be closed when you say yes.',
  closeYes: 'Yes, close it',
  reopenNo: 'No, reopen it',
  talkToAssistant: 'Talk to an assistant',
  assistDept: 'Concerned department',
  assistCallDept: 'Call department helpline',
  assistGeneral: 'General grievance helpline',
  assistVisit: 'Prefer in person? Staff at your Grama/Ward Sachivalayam can help you too.',

  // status names
  st_REGISTERED: 'Registered',
  st_CLASSIFIED: 'Categorised',
  st_ASSIGNED: 'Assigned to officer',
  st_UNDER_ENQUIRY: 'In progress',
  st_ACTION_TAKEN: 'Action taken',
  st_RESOLVED: 'Resolved',
  st_CLOSED: 'Closed',
  st_REOPENED: 'Reopened',
  st_ON_HOLD: 'On hold',
  st_REROUTED: 'Rerouted',
  st_MERGED: 'Merged',
  st_REJECTED: 'Rejected',

  // why better
  whyBetter: 'Why this is better',
  why1: 'Speak in your language — no reading or typing needed',
  why2: 'Tamper-proof record you can verify yourself',
  why3: 'No complaint is closed without your confirmation',
  why4: 'Track every step, get plain-language updates',

  // unified login / landing (v3)
  startLanguage: 'First, choose your language',
  startLanguageHelp: 'Every question will be asked in this language. You can change it anytime.',
  startHere: 'Start here',
  citizenLogin: 'Citizen login',
  staffLogin: 'Staff login',
  citizenLoginHint: 'Login with your mobile number to file or track a complaint.',
  staffLoginHint: 'Officers & Sachivalayam staff sign in with their work account.',
  backToCitizen: 'Back to citizen login',
  continueAs: 'Continue as',
  trustedBy: 'A Government of India initiative for fair, fast, transparent grievance redressal.',
  liveStats: 'Live pilot',
  statResolved: 'Resolved',
  statOnTime: 'On-time',
  statLanguages: 'Languages',
  statTamperProof: 'Tamper-proof',

  // voice (v3)
  speakNow: 'Speak now',
  tapMicToSpeak: 'Tap the mic and speak in your language',
  micDenied: 'Microphone blocked. Allow mic access in your browser, then tap again.',
  micError: 'Could not hear you. Please try again or type your answer.',
  micUnsupported: 'Voice typing is not supported on this browser — please type.',
  listenAgain: 'Listen again',
  playing: 'Playing…',
  yourAnswer: 'Your answer',

  // documents (v3)
  qDocuments: 'Add supporting documents',
  qDocumentsHelp: 'Photos of bills, letters, ID or the problem. You can skip this.',
  addDocument: 'Add a document / photo',
  addPhoto: 'Take or upload a photo',
  documentsAttached: '{n} document(s) attached',
  uploading: 'Uploading…',
  removeDoc: 'Remove',
  noDocuments: 'No documents added yet',

  // dashboard extras (v3)
  goodToSee: 'Good to see you',
  dashboardSubtitle: 'File a new complaint, or check how your existing ones are going.',
  openComplaints: 'Open',
  resolvedComplaints: 'Resolved',
  needsYou: 'Needs your confirmation',
  quickActions: 'Quick actions',
  helpTitle: 'Need a hand?',
  helpDesc: 'Call 1902 (toll-free) or visit your Sachivalayam — staff can file for you.',

  // ── Saarthi 2.0 — voice-first intake (method choice, no language picker) ──
  howToComplain: 'How would you like to complain?',
  speakComplaint: 'Speak your complaint',
  speakComplaintHint: 'Any Indian language. We detect it automatically.',
  typeComplaint: 'Type your complaint',
  typeComplaintHint: 'Any script — Telugu, हिन्दी, தமிழ், English…',
  noDeptNeeded: 'No forms. No department lists. Our AI reads your problem and sends it to the right department.',
  recListening: "Listening… speak freely. We won't interrupt.",
  recTapToStart: 'Tap to start speaking',
  recStop: 'Stop',
  recPause: 'Pause',
  recResume: 'Resume',
  recRedo: 'Re-record',
  recUseIt: 'Use this recording',
  recWarn8: 'Approaching the 10-minute limit — please finish your point.',
  recCountdown: 'Recording will stop in {n} s',
  recDetected: 'Detected',
  recReview: 'Listen to your recording',
  recKeepAudio: 'Your original voice recording travels with the complaint to the department — it is your evidence.',
  // First-login onboarding + profile
  onbTitle: 'Welcome! Tell us about yourself',
  onbSubtitle: 'Just once — every complaint after this is prefilled with your details. You can change them any time from your profile.',
  onbSave: 'Save & continue',
  onbNote: 'Your details stay with the grievance system only and are shared with the officer handling your complaint.',
  profTitle: 'My profile',
  profSubtitle: 'These details prefill every complaint you file',
  profSave: 'Save changes',
  profSaved: 'Profile updated',
  profName: 'Full name',
  profNamePh: 'e.g. Ramesh Kumar',
  profGender: 'Gender',
  profGender_MALE: 'Male',
  profGender_FEMALE: 'Female',
  profGender_OTHER: 'Other',
  profDistrict: 'District',
  profMandal: 'Mandal',
  profVillage: 'Village / Ward',
  profHouse: 'House number (optional)',
  asrAutoHint: 'Speak in any language — we recognise it from your voice and write it in your own script.',
  asrDegraded: 'Voice-to-text is unreachable right now — your recording still travels with the complaint, and the server will transcribe it.',
  speakLangPick: 'I will speak in',
  transcribing: 'converting your voice to text…',
  typeHere: 'Describe your problem in any language…',
  liveTranscript: 'What we heard',
  yourLocation: 'Your live location',
  locationWhy: 'Shared with the officer so they can find the exact spot.',
  locationCapture: 'Attach my location',
  locationCaptured: 'Location attached (±{m} m)',
  locationDenied: 'Location not shared — the officer will use your village/ward instead.',
  locationSkip: 'Skip',
  whereIsIt: 'Where is the problem?',
  submitComplaint: 'Submit complaint',
  aiRouting: 'Saarthi AI is reading your complaint…',
  aiRouted: 'Routed automatically by AI',
  aiRoutedTo: 'Sent to {dept}',
  aiConfidencePct: 'AI confidence {p}%',
  aiNeedsHuman: 'A District Grievance Officer will confirm the department within 4 working hours',
  aiMergedTitle: 'Already reported at this spot',
  aiMergedBody: '{n} citizens have reported this issue here. Your report was added to case {ysr} and raised its priority. You will be notified when it is resolved.',
  yourOfficer: 'Your officer',
  severityLabel: 'Severity',
  urgencyLabel: 'Urgency',
  sev_LOW: 'Low',
  sev_MEDIUM: 'Medium',
  sev_HIGH: 'High',
  sev_CRITICAL: 'Critical',
  urg_LOW: 'Low',
  urg_MEDIUM: 'Medium',
  urg_HIGH: 'High',
  urg_IMMEDIATE: 'Immediate',
  st_PENDING_VERIFICATION: 'Human verification',
  st_QUICK_DESK_REVIEW: 'Desk review',
  reportedBy: 'Reported by {n} citizens',
  routedByAi: 'Routed by AI',
  routedByHuman: 'Verified by officer',

  // ── Saarthi 2.0 — track page ──
  officerHandling: 'Officer handling your case',
  callDepartment: 'Call department',
  copilotTitle: 'Saarthi assistant',
  copilotHint: 'Ask anything about your complaint — in your language.',
  copilotPlaceholder: 'e.g. When will this be fixed? What are my rights?',
  copilotSend: 'Ask',
  copilotThinking: 'Thinking…',
  copilotSources: 'Sources',
  reopenTitle: 'Not satisfied? Ask to reopen',
  reopenWhy: 'Tell us why — this goes to a senior officer for a quick desk review.',
  reopenTypeReason: 'Type your reason',
  reopenSpeakReason: 'Speak your reason',
  reopenReasonPlaceholder: 'What is still wrong? e.g. the work was not actually done…',
  reopenSubmit: 'Send for desk review',
  reopenPendingNote: 'Your reopen request is with {name} for a quick desk review.',
  reopenApprovedNote: 'Reopen approved by {name} — your case is escalated to a higher officer.',
  reopenUpheldNote: 'After review, {name} upheld the closure: {note}',
  yourVoiceNote: 'Your voice recording',
  blockchainProof: 'Blockchain record',
  viewChain: 'View the chain',
  chainIntro: 'Every step of your case is a sealed block. Each block is chained to the one before — nobody can silently edit history.',
  blockVerified: 'verified',
  merged_into: 'This report was merged into case {ysr}',
  consentNote: 'Your voice, text and location are recorded with your consent and shared only with the government department responsible for resolving your complaint.',
};

export type StringKey = keyof typeof en;
